name: publish-book

on: 

  workflow_dispatch:

env:
  NB_KERNEL: python
  NMA_REPO: brainCodeCamp
  NMA_MAIN_BRANCH: main

permissions:
  contents: write
# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter-book ghp-import

      - name: Build book
        run: |
          jupyter-book build .
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build/html